# Generated by Django 6.0.6 on 2026-07-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('roadmap', 'Roadmap'), ('ebook', 'E-Book'), ('template', 'Template'), ('cheatsheet', 'Cheat Sheet'), ('guide', 'Guide'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('ai', 'AI / Machine Learning'), ('cybersecurity', 'Cybersecurity'), ('webdev', 'Web Development'), ('mobiledev', 'Mobile Development'), ('career', 'Career Advice'), ('design', 'Design / UI-UX'), ('devops', 'DevOps'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/files/'),
        ),
    ]
